### PR TITLE
updated major version in version file to reflect java 17 changes

### PR DESCRIPTION
**Pull request by hselvakumar**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by bcullerton — APPROVED** [review]

**Pull request merged**
